config-version: 2

name: dbt_sandbox_se
version: "0.0.1"
require-dbt-version: ">=1.5.0"

dbt-cloud:
    project-id: 70403103985012

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  dbt_sandbox_se:
    +schema: raw

models:
  dbt_sandbox_se:
    staging:
      +materialized: view
      +group: analytics_engineering
    marts:
      +materialized: table
      +group: analytics_engineering

semantic-models:
  dbt_sandbox_se:
    +group: business_intelligence

metrics:
  dbt_sandbox_se:
    +group: business_intelligence
